const data = {
  products: [
    {
      _id: "1",
      name: "Ralph Lauren shirt",
      slug: "ralph-lauren-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 15,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      _id: "2",
      name: "Tommy Hilfiger shirt",
      slug: "tommy-hilfiger-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 110,
      countInStock: 17,
      rating: 4.4,
      numReviews: 12,
      description: "very comfy",
    },
    {
      _id: "3",
      name: "Ralph Lauren pants",
      slug: "ralph-lauren-pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 80,
      countInStock: 18,
      rating: 4.7,
      numReviews: 25,
      description: "Definitly worth it",
    },
    {
      _id: "4",
      name: "Tommy Hilfiger pants",
      slug: "tommy-hilfiger-pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 70,
      countInStock: 0,
      rating: 3.9,
      numReviews: 10,
      description: "pretty good",
    },
  ],
};
export default data;
